### ISSUE TITLE
k3s vs k8s versioning

### ISSUE THREAD

**Issue by mkmik** [zawachte/cluster-api-k3s#19]
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KThreesControlPlane
metadata:
  name: k3-test-13-control-plane
spec:
  version: v1.21.5+k3s2
...
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: k3-test-13
spec:
  controlPlaneLoadBalancer:
    healthCheckProtocol: TCP
  imageLookupBaseOS: ubuntu-20.04
  imageLookupFormat: capa-ami-{{.BaseOS}}-1.21.5-*
```
